<a href="https://colab.research.google.com/github/rohitshyam/python/blob/main/reshaping_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Reshaping Numpy Arrays**
import statements

In [ ]:
import numpy as np

Create the array and print the array and its shape

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


Reshape it

In [ ]:
a=a.reshape(4,3 )# 4 X 3
print(a)
print(a.shape)
a=a.reshape(2,3,2 )# 2 X 3 X 2
print(a)
print(a.shape)
a=a.reshape(1,12 )# 1 X 12
print(a)
print(a.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)


Reshape it using negative indexes

In [ ]:
a=a.reshape(-1,3 )# 4 X 3. This will give the remaining values to the first dimension. Any -ve number is allowed
print(a)
print(a.shape)
a=a.reshape(2,3,-2 )# 2 X 3 X 2
print(a)
print(a.shape)
a=a.reshape(1,-1 )# 12 X 1
print(a)
print(a.shape)
a=a.reshape(-1,12 )# 1 X 12
print(a)
print(a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)
